# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170309_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberof', models.IntegerField(default=0)),
                ('page', models.CharField(max_length=200)),
            ],
        ),
    ]
